name: collabio
description: A platform to enable developers and designers to find projects they can collaborate on.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  timeago: ^3.5.0
  flutter_markdown: ^0.6.17
  sqflite: ^2.2.8
  path: ^1.8.3
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  device_preview: ^1.0.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  intl: ^0.18.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true